/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"
#include "USBuart.h"
#include "Trace.h"
#include <Ntstrsafe.h>

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, ElektorUSBuartKMDFCreateDevice)
#pragma alloc_text (PAGE, ElektorUSBuartKMDFEvtDevicePrepareHardware)
#endif

// 32-bit device index (for numbering legacy device names)
// This is a critical region, only to be accessed through Interlocked functions.
LONG device_bitmap = 0;

// Legacy device name
#define SYMLINK_NAME L"\\DosDevices\\usbuart_"
#define SYMLINK_BUFFER_LENGTH sizeof(SYMLINK_NAME L"XX") / sizeof(WCHAR)

NTSTATUS
AcquireDeviceIndex(
	_Out_ ULONG *deviceId
)
/*++
  Acquire a device id
--*/
{
	// Find an available device id, starting from 0
	ULONG index = 0;
	while (index < sizeof(device_bitmap)) {
		if (!InterlockedBitTestAndSet(&device_bitmap, index)) {
			// Found, return
			*deviceId = index;
			return STATUS_SUCCESS;
		}
		else
			index++;
	}
	// More that 32 devices connected
	return STATUS_INSUFFICIENT_RESOURCES;
}

NTSTATUS
ReleaseDeviceIndex(
	_In_ ULONG index
)
/*++
  Release the device id
--*/
{
	if (InterlockedBitTestAndReset(&device_bitmap, index)) {
		return STATUS_SUCCESS;
	} else {
		return STATUS_UNSUCCESSFUL;
	}
}

NTSTATUS
ElektorUSBuartKMDFCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_OBJECT_ATTRIBUTES   deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    pnpPowerCallbacks.EvtDevicePrepareHardware = ElektorUSBuartKMDFEvtDevicePrepareHardware;
	pnpPowerCallbacks.EvtDeviceReleaseHardware = ElektorUSBuartKMDFEvtDeviceReleaseHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

	// Continue initialization
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

		//
		// Assign device index
		//
		status = AcquireDeviceIndex(&deviceContext->DeviceIndex);

		if (!NT_SUCCESS(status)) {
			return status;
		}

		//
		// Create a symbolic link for the control object so that
		// usermode can open the device.
		//
		DECLARE_UNICODE_STRING_SIZE(symlink, SYMLINK_BUFFER_LENGTH);
		status = RtlUnicodeStringPrintf(&symlink, SYMLINK_NAME L"%d", deviceContext->DeviceIndex);

		status = WdfDeviceCreateSymbolicLink(
			device,
			&symlink
		);

		if (!NT_SUCCESS(status)) {
			return status;
		}

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_ElektorUSBuartKMDF,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = ElektorUSBuartKMDFQueueInitialize(device);
        }
    }

    return status;
}

NTSTATUS
ElektorUSBuartKMDFEvtDevicePrepareHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourceList,
    _In_ WDFCMRESLIST ResourceListTranslated
    )
/*++

Routine Description:

    In this callback, the driver does whatever is necessary to make the
    hardware ready to use.  In the case of a USB device, this involves
    reading and selecting descriptors.

Arguments:

    Device - handle to a device

Return Value:

    NT status value

--*/
{
    NTSTATUS status;
    PDEVICE_CONTEXT pDeviceContext;
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS configParams;

    UNREFERENCED_PARAMETER(ResourceList);
    UNREFERENCED_PARAMETER(ResourceListTranslated);

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Entry");

    status = STATUS_SUCCESS;
    pDeviceContext = DeviceGetContext(Device);

    //
    // Create a USB device handle so that we can communicate with the
    // underlying USB stack. The WDFUSBDEVICE handle is used to query,
    // configure, and manage all aspects of the USB device.
    // These aspects include device properties, bus properties,
    // and I/O creation and synchronization. We only create the device the first time
    // PrepareHardware is called. If the device is restarted by pnp manager
    // for resource rebalance, we will use the same device handle but then select
    // the interfaces again because the USB stack could reconfigure the device on
    // restart.
    //
    if (pDeviceContext->UsbDevice == NULL) {

        status = WdfUsbTargetDeviceCreate(Device,
                                                    WDF_NO_OBJECT_ATTRIBUTES,
                                                    &pDeviceContext->UsbDevice
                                                    );

        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
                        "WdfUsbTargetDeviceCreateWithParameters failed 0x%x", status);
            return status;
        }
    }

    //
    // Select the first configuration of the device, using the first alternate
    // setting of each interface
    //
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS_INIT_MULTIPLE_INTERFACES(&configParams,
                                                                 0,
                                                                 NULL
                                                                 );
    status = WdfUsbTargetDeviceSelectConfig(pDeviceContext->UsbDevice,
                                            WDF_NO_OBJECT_ATTRIBUTES,
                                            &configParams
                                            );

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
                    "WdfUsbTargetDeviceSelectConfig failed 0x%x", status);
        return status;
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Exit");

    return status;
}



NTSTATUS ElektorUSBuartKMDFEvtDeviceReleaseHardware(
	_In_ WDFDEVICE    Device,
	_In_ WDFCMRESLIST ResourcesTranslated
	)
{
	NTSTATUS status;
	PDEVICE_CONTEXT deviceContext;
	deviceContext = DeviceGetContext(Device);

	// Release device id
	status = ReleaseDeviceIndex(deviceContext->DeviceIndex);

	(void)ResourcesTranslated;

	return status;
}
